// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package base

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type UserTUser struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Name      string
	Age       int32
	Document  string
}
