// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package base

import (
	"context"
)

type Querier interface {
	Insert(ctx context.Context, arg *InsertParams) (*InsertRow, error)
}

var _ Querier = (*Queries)(nil)
