version: "2"
sql:
  - schema: "../schema.sql"
    queries: "queries.sql"
    engine: "postgresql"
    gen:
      go:
        out: ".."
        package: "base"
        emit_interface: true
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        output_models_file_name: "model.go"
        emit_exact_table_names: true